### ISSUE TITLE
Fix Internet Explorer 11

### ISSUE THREAD

**Issue by rhpijnacker** [rhpijnacker/intern-cucumber#1]
Running the cucumber plugin in the browser does not work on IE11.

**Comment by jason0x43** [comment]
It sounds like their issue is with bundling dependencies. If you build the plugin as a webpack bundle is this still an issue?

**Comment by rhpijnacker** [comment]
@jason0x43 The browser plugin is actually bundled with webpack. I tried to use babel to transpile the cucumber bundle (built with browserify) to es5, but did not get it to work (yet).

**Comment by rhpijnacker** [comment]
Using the `babel-engine-plugin` helped getting the dependency babelified.
Even though that does not solve all issues on IE11 (see #10) i'm closing this.
