### ISSUE TITLE
How to configure World?

### ISSUE THREAD

**Issue by Jehu** [rhpijnacker/intern-cucumber#11]
What is the best way to configure ‘World‘  when using intern-cucumber?

**Comment by rhpijnacker** [comment]
In principle no different from the way cucumber-js does it.
Get the `setWorldConstructor` method from the package and use it to initialize the world.
One caveat: intern-cucumber also sets a world contructor itself. This world constructor makes sure to pass the .remote property. Setting your own would overwrite that.

**Comment by Jehu** [comment]
thanks a lot
