### ISSUE TITLE
How do I import Before, After?

### ISSUE THREAD

**Issue by dsb3ar** [rhpijnacker/intern-cucumber#13]
I am trying to import "Before" and "After" in my step definition file using 

`const { registerCucumber, Given, When, Then, After, Before } = intern.getPlugin<CucumberInterface>('interface.cucumber');`

But Before and After don't exist in CucumberInterface

Can you help with how to import these functions?

Many thanks

**Comment by rhpijnacker** [comment]
Weird, they should be there. Do you get some error? Or are the variables "undefined"?

**Comment by dsb3ar** [comment]
I get the following error

`(TS) Type 'CucmberInterface' has no property 'After' and no string index signature.`

**Comment by rhpijnacker** [comment]
Ah, it looks like the TypeScript interface does not expose the After, AfterAll, Before and BeforeAll properties.
Could you see if updating the .d.ts file with these methods helps?

**Comment by dsb3ar** [comment]
I have updated .d.ts and it recognises the Before etc call, can you advise what the parameters should be, I presume they are different to the Given, When, Then but I could be wrong.  I'm a tester not a dev so apologies if I miss something obvious.  Appreciate your help and speedy replies. Thanks

**Comment by dsb3ar** [comment]
Just to clarify, is this how .d.ts should be?

export interface World {
    [key: string]: any;
}
export type StepDefinitionCode = (this: World, ...stepArgs: any[]) => any;
export type StepDefinitionInitializer = () => void;

export default function registerCucumber(
	name: string,
	featureSource: string,
	...stepDefinitionInitializers: StepDefinitionInitializer[]
): void;

export function Given(pattern: RegExp | string, code: StepDefinitionCode): void;
export function Then(pattern: RegExp | string, code: StepDefinitionCode): void;
export function When(pattern: RegExp | string, code: StepDefinitionCode): void;
export function After(pattern: RegExp | string, code: StepDefinitionCode): void;
export function AfterAll(pattern: RegExp | string, code: StepDefinitionCode): void;
export function Before(pattern: RegExp | string, code: StepDefinitionCode): void;
export function BeforeAll(pattern: RegExp | string, code: StepDefinitionCode): void;

export interface CucumberInterface {
	registerCucumber(
		name: string,
		featureSource: string,
		...stepDefinitionInitializers: any[]
	): void;
	
	Given(pattern: RegExp | string, code: StepDefinitionCode): void;
	Then(pattern: RegExp | string, code: StepDefinitionCode): void;
	When(pattern: RegExp | string, code: StepDefinitionCode): void;
	After(pattern: RegExp | string, code: StepDefinitionCode): void;
	AfterAll(pattern: RegExp | string, code: StepDefinitionCode): void;
	Before(pattern: RegExp | string, code: StepDefinitionCode): void;
	BeforeAll(pattern: RegExp | string, code: StepDefinitionCode): void;

**Comment by rhpijnacker** [comment]
I based the typescript typings on https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/cucumber/v3/index.d.ts. So you may want to have a look at that.

**Comment by dsb3ar** [comment]
Thanks for the info.  If i'm understanding this right, plugin.js in the browser folder contains the cucumber functions and rather than translating this to typescript you use plugins.d.ts which contains the type annotations.  So if I get the correct syntax in the .d.ts file it will call the underlying .js.

**Comment by rhpijnacker** [comment]
Yes. Reimplementing in Typescript is on the todo list.
Until that happens it is just plain old .js and the .d.ts provides the Typescript types.

**Comment by rhpijnacker** [comment]
Did you get this running with updated types?
If so, could you share this via a PR?
