### ISSUE TITLE
How do I use common step defintions, non feature specific

### ISSUE THREAD

**Issue by dsb3ar** [rhpijnacker/intern-cucumber#15]
I am trying to create a common step definition file containing re-usable steps and then import these steps into a feature specific step file.

`let featureSource = readFileSync("features/blah.feature", "utf-8");` 
only allows my step files to mimic my feature file, where as I would like my step files to be page related and handle importing common step definitions.

How do you deal with common step definitions?

**Comment by rhpijnacker** [comment]
It is possible to pass in multiple step-definition functions to the `registerCucumber` call.
That means you can load these from separate files, which should enable re-use.
