### ISSUE TITLE
Make Intern a peerDependency rather than a dependency

### ISSUE THREAD

**Issue by jason0x43** [rhpijnacker/intern-cucumber#4]
Intern should be a peerDependency of a plugin rather than a direct dependency. (It will probably also need to be a devDependency, particularly if you move to TypeScript.)

**Comment by rhpijnacker** [comment]
@jason0x43 Good idea! 
Would that be a matter of changing
`
    "dependencies": {
        "intern": "^4.1.5"
    }
`
into
`"peerDependencies": {
  "intern": "~4.1.5"
}`
(relaxing the exact version)?
I tried this, but now npm complains:
`npm WARN intern-cucumber@0.0.3 requires a peer of intern@~4.1.5 but none was installed.`

**Comment by rhpijnacker** [comment]
I think I got it right. @jason0x43 can you confirm?
