### ISSUE TITLE
Mapping cucumber events to Intern

### ISSUE THREAD

**Issue by jason0x43** [rhpijnacker/intern-cucumber#5]
The current code has the following mapping from Cucumber to Intern:

| Cucumber | Intern |
|----------|--------|
| test-run-started | suiteStart |
| test-run-finished | suiteEnd |
| test-case-started | suiteStart |
| test-case-finished | suiteEnd |
| test-step-started | testStart |
| test-step-finished | testEnd |

I think we probably want the `test-case` events to map to Intern test events, and we don't really care about test steps (in that they don't map to anything directly in Intern).

```
@feature
Feature: A feature.      <-- equivalent to an Intern Suite, if
                             there are events for this
  @scenario
  Scenario: A scenario   <-- equivalent to an Intern Test
    Given a step         <-- step in the test
```

The `test-run` events don't map to Intern directly, either, but if the plugin starts a new instance of Cucumber for each suite, then it does make sense to map them to Intern suite events.

**Comment by rhpijnacker** [comment]
@jason0x43 Thanks for taking the time to have a look at this project.
The way you suggest is actually how the intern3 integration was implemented. 
I thought it would have some added value to be able to inspect the success of the individual steps. That way, when a scenario fails, you can easily inspect on which step this happened.
However, providing the right text in the report could also help out here.
