### ISSUE TITLE
Documentation Accuracy + Example?

### ISSUE THREAD

**Issue by kenthannigan** [rhpijnacker/intern-cucumber#6]
I'm having trouble getting this cucumber/intern interface to work and would really appreciate some more thorough documentation or an example project to reference. 

According to the documentation I am supposed to add the following to intern.json:
```
    "browser": {
        "plugins": {
            "intern-cucumber/_build/browser/plugin.js"
        }
    }
    "node": {
        "plugins": {
            "intern-cucumber/src/plugin.js"
        }
    }
```
However, those files do not exist at the given paths. It also does not appear to be valid json...  Here is what my directory structure looks like when installed via `npm install intern-cucumber`:
![image](https://user-images.githubusercontent.com/16963630/35585208-56f615ac-05c5-11e8-9d58-a37aef3abce4.png)

So I'm assuming the portion added to intern.json should actually be the following:
```
    "browser": {
        "plugins": "intern-cucumber/browser/plugin.js"
    },
    "node": {
        "plugins": "intern-cucumber/plugin.js"
    }
```

After making that change I am running into all kinds of errors trying to get my tests set up with registerSupport. This is where an example or more thorough documentation would be helpful. 

Here is my stack trace, which is almost certainly a result of me not understanding what registerSupport expects:
```
TypeError: Path must be a string. Received undefined
  at assertPath  <path.js:28:11>
  at Object.relative  <path.js:568:5>
  at getDefinitionLineAndUri  <node_modules\cucumber\src\support_code_library_builder\define_helpers.js:103:5>
  at <node_modules\cucumber\src\support_code_library_builder\define_helpers.js:61:37>
  at Object.<anonymous>  <tests\functional\cuc\cucTest.js:14:1>
  at Module._compile  <module.js:643:30>
  at Object.Module._extensions..js  <module.js:654:10>
  at Module.load  <module.js:556:32>
  at tryModuleLoad  <module.js:499:12>
  at Function.Module._load  <module.js:491:3>
  at Module.require  <module.js:587:17>
  at require  <internal\module.js:11:18>
  at Node.loadScript  <src\lib\executors\Node.ts:256:5>
  at Node._loader  <src\loaders\default.ts:10:16>
  at Node._loadFunctionalSuites  <src\lib\executors\Node.ts:588:27>
  at <src\lib\executors\Node.ts:752:18>
```

Any help is greatly appreciated.

**Comment by kenthannigan** [comment]
I eventually determined registerSupport expects (testName(which doesn't have to match anything), feature file read into a variable, a function wrapping your test implementation). The documentation wasn't very clear about that and it may help others to be more explicit. For example, I certainly didn't expect to have to read the feature file into a variable, I was expecting that to be a path to the feature file.

**Comment by rhpijnacker** [comment]
@kenthannigan Thanks for taking a look at this project. I will certainly take your suggestion to create an example project at heart.
Being able to pass the feature filename as a parameter is actually a nice idea.
The reason I did not start out like that is because we are running these tests in the browser and using the dojo/text! plugin to load the text. 
I will have a look at how we can make both variations possible.

**Comment by rhpijnacker** [comment]
@kenthannigan Could you have a look at https://github.com/rhpijnacker/intern-cucumber-examples?

**Comment by kenthannigan** [comment]
Thanks for taking the time to make those example projects! I would also like to see how you are using intern within your tests. I'm currently doing this horrendous operation to get remote in order to use intern functionality: 
```js
var remote = intern._sessionSuites[0].tests[0].tests[0].tests[0].remote;
```
other intern interfaces, such as tdd, simply pass remote to you. 

I was also wondering if this interface has any sort of beforeFeature() or an equivalent function I can use within a test, to run code prior to running the steps of the feature. I have an operation I want to run at the start of every test(passing data defined in the test.js file), but don't want it to be an actual step of the test.

**Comment by rhpijnacker** [comment]
Could you try version 0.0.5 ?
I've added the "remote" property as part of the World for functional tests.
So, now you should be able to do:
```
  Given('step text', function() { this.remote. ...; });
```
(make sure to use ```function``` and not ```() =>``` to make sure the ```thiis``` context is bound correctly).

**Comment by rhpijnacker** [comment]
Better yet, try 0.0.6.
I've added additional cucumber methods like ```Before```, ```BeforeAll```, ```After```, etc.

**Comment by kenthannigan** [comment]
Exactly what I was looking for. Thank you.

**Comment by kenthannigan** [comment]
this.remote is undefined for me. **this** evaluates to World, it just doesn't contain remote. 
this = World {attach: ƒ, parameters: undefined}
I set a breakpoint on the following line of cucumber.js:
```js
let suite = _createSuite(name, featureSource, stepDefinitionInitializers, parent.remote);
```
and parent itself is defined, but parent.remote is undefined. 

Any idea what could be causing this? I'd be more than happy to share additional info if necessary.

**Comment by rhpijnacker** [comment]
Somehow I can't get a functionalSuite to load in conjunction with the cucumber plugin.
Could you share your intern.json so I can have a look how you set this up?

**Comment by kenthannigan** [comment]
### intern.json
```json
{
    "functionalSuites": "tests/cucExamples/cucTest.js",
    "environments": [
        {
            "browserName": "chrome"
        }
    ],
    "reporters": [
        {
            "name": "junit",
            "filename": "report.xml"
        },
        "runner"
    ],
    "tunnelOptions": {
        "version": "3.8.1",
        "drivers": [
            {
                "name": "chrome"
            }
        ]
    },
    "browser": {
        "plugins": "intern-cucumber/browser/plugin.js"
    },
    "node": {
        "plugins": "intern-cucumber/plugin.js"
    }
}
```

**Comment by rhpijnacker** [comment]
Could you try again with 0.0.8?
Turns out the ```.remote``` is only available on the suite when it is actually running, not yet during creation time. This should be fixed now.

**Comment by rhpijnacker** [comment]
Small update: 0.0.9
I also updated the dojo-example to include a functional test.
This one works for me.

**Comment by kenthannigan** [comment]
this.remote works for me now. Thanks.
