### ISSUE TITLE
Error Reporting

### ISSUE THREAD

**Issue by kenthannigan** [rhpijnacker/intern-cucumber#9]
Would it be possible to either completely disable cucumber's issue formatting or at least stop it from erroring out due to **pickle** being undefined in `formatIssue()` within `issue_helpers.js`? 

It's a bit difficult to see the relevant error message for a test, when issue_helpers throws its own error above and below it each time, as seen below:
![errors](https://user-images.githubusercontent.com/16963630/37537612-83564716-2924-11e8-8067-b54a62036a4c.png)

Preferably, the only thing printed would be the error message in the middle.

**Comment by kenthannigan** [comment]
Calling process.exit(0) in the AfterAll() hook kills the process before the junk errors are reported, so I'm using that as a workaround for now. It displays the real error and then exits immediately.

**Comment by jason0x43** [comment]
You can cleanup stack traces quite a bit by setting Intern's `filterErrorStack` config property to `true`.
